# JupyterLite で学ぶ pandas 初級チュートリアル

このノートブックは、**JupyterLite（ブラウザだけで動く Jupyter 環境）** 上で、
データ分析ライブラリ **pandas** の基礎を一から学ぶためのチュートリアルです。

## 対象者
- Python の基本（変数、リスト、辞書、ループなど）を理解している方
- pandas を初めて使う方、または基礎を復習したい方

## このチュートリアルで学ぶこと
1. pandas とは何か
2. Series の基本操作
3. DataFrame の作成と基本操作
4. データの読み込み・書き出し
5. データの選択とスライス
6. 条件によるフィルタリング
7. 基本的な統計量の計算
8. データの並べ替え

## 0. 環境準備（JupyterLite 用）

まず、必要なライブラリをインストールします。

In [1]:
# JupyterLite 用のパッケージインストール
try:
    import piplite
    await piplite.install(["numpy", "pandas", "matplotlib", "japanize-matplotlib-jlite"])
except ImportError:
    pass

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import japanize_matplotlib_jlite  # 日本語表示用

# 表示設定
pd.set_option("display.max_rows", 10)
print(f"pandas バージョン: {pd.__version__}")

pandas バージョン: 2.3.3

---
## 1. pandas とは何か

**pandas** は、Python でデータ分析を行うためのライブラリです。

### pandas の特徴
- **表形式のデータ**（Excel のスプレッドシートのようなもの）を簡単に扱える
- CSV、Excel、SQL などさまざまな形式のデータを読み込める
- データのフィルタリング、集計、変換が直感的に行える
- NumPy や Matplotlib との連携が良い

### pandas の 2 つの主要なデータ構造
| データ構造 | 説明 | イメージ |
|-----------|------|----------|
| **Series** | 1次元のラベル付き配列 | Excel の 1 列分 |
| **DataFrame** | 2次元のラベル付き表 | Excel のシート全体 |

---
## 2. Series の基本

**Series** は、インデックス（ラベル）付きの 1 次元配列です。

### 2.1 Series の作成

In [3]:
# リストから Series を作成
s1 = pd.Series([10, 20, 30, 40, 50])
print("リストから作成した Series:")
print(s1)

リストから作成した Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# インデックスを指定して作成
s2 = pd.Series([85, 92, 78, 95], index=["数学", "英語", "国語", "理科"])
print("インデックス付きの Series:")
print(s2)

インデックス付きの Series:
数学    85
英語    92
国語    78
理科    95
dtype: int64

In [5]:
# 辞書から Series を作成
prices = {"りんご": 150, "バナナ": 100, "みかん": 80, "ぶどう": 300}
s3 = pd.Series(prices)
print("辞書から作成した Series:")
print(s3)

辞書から作成した Series:
りんご    150
バナナ    100
みかん     80
ぶどう    300
dtype: int64

### 2.2 Series の基本属性

In [6]:
print(f"値（values）: {s2.values}")
print(f"インデックス（index）: {list(s2.index)}")
print(f"データ型（dtype）: {s2.dtype}")
print(f"要素数（size）: {s2.size}")

値（values）: [85 92 78 95]
インデックス（index）: ['数学', '英語', '国語', '理科']
データ型（dtype）: int64
要素数（size）: 4

### 2.3 Series の要素へのアクセス

In [7]:
# ラベルでアクセス
print(f"数学の点数: {s2['数学']}")

# 位置（番号）でアクセス
print(f"最初の要素: {s2.iloc[0]}")

# スライス
print(f"\n最初の2つ:")
print(s2.iloc[:2])

数学の点数: 85
最初の要素: 85

最初の2つ:
数学    85
英語    92
dtype: int64

### 2.4 Series の演算

In [8]:
# 全要素に対する演算
print("元の点数:")
print(s2)
print("\n全員に +5 点:")
print(s2 + 5)

print("\n点数を 100 で割って割合に:")
print(s2 / 100)

元の点数:
数学    85
英語    92
国語    78
理科    95
dtype: int64

全員に +5 点:
数学     90
英語     97
国語     83
理科    100
dtype: int64

点数を 100 で割って割合に:
数学    0.85
英語    0.92
国語    0.78
理科    0.95
dtype: float64

### 📝 2章 練習問題

1. 自分の好きな食べ物を 5 つ選び、その値段（円）を Series として作成しなさい。インデックスには食べ物の名前を使うこと。
2. 作成した Series の平均値、最大値、最小値を求めなさい（ヒント: `.mean()`, `.max()`, `.min()` メソッドを使う）。
3. 全ての値段を 1.1 倍（消費税込み）にした新しい Series を作成しなさい。

In [9]:
# 練習問題の解答欄

---
## 3. DataFrame の作成と基本操作

**DataFrame** は、行と列を持つ 2 次元の表形式データです。
Excel のスプレッドシートや SQL のテーブルに似ています。

### 3.1 DataFrame の作成方法

In [10]:
# 辞書から DataFrame を作成（最もよく使う方法）
data = {
    "名前": ["田中", "佐藤", "鈴木", "高橋", "伊藤"],
    "年齢": [22, 25, 30, 28, 24],
    "部署": ["営業", "開発", "営業", "人事", "開発"],
    "給与": [300000, 350000, 320000, 310000, 340000]
}

df = pd.DataFrame(data)
df

   名前  年齢  部署      給与
0  田中  22  営業  300000
1  佐藤  25  開発  350000
2  鈴木  30  営業  320000
3  高橋  28  人事  310000
4  伊藤  24  開発  340000

In [11]:
# リストのリストから作成
data_list = [
    ["東京", 1400, 2194],
    ["大阪", 884, 1905],
    ["愛知", 755, 5173],
    ["北海道", 530, 83424]
]

df2 = pd.DataFrame(data_list, columns=["都道府県", "人口（万人）", "面積（km²）"])
df2

  都道府県  人口（万人）  面積（km²）
0   東京    1400     2194
1   大阪     884     1905
2   愛知     755     5173
3  北海道     530    83424

### 3.2 DataFrame の基本属性

In [12]:
print(f"形状（shape）: {df.shape}")
print(f"列名（columns）: {list(df.columns)}")
print(f"インデックス（index）: {list(df.index)}")
print(f"\nデータ型（dtypes）:")
print(df.dtypes)

形状（shape）: (5, 4)
列名（columns）: ['名前', '年齢', '部署', '給与']
インデックス（index）: [0, 1, 2, 3, 4]

データ型（dtypes）:
名前    object
年齢     int64
部署    object
給与     int64
dtype: object

### 3.3 DataFrame の概要を確認

In [13]:
# 最初の数行を表示
print("最初の 3 行:")
df.head(3)

最初の 3 行:

   名前  年齢  部署      給与
0  田中  22  営業  300000
1  佐藤  25  開発  350000
2  鈴木  30  営業  320000

In [14]:
# 最後の数行を表示
print("最後の 2 行:")
df.tail(2)

最後の 2 行:

   名前  年齢  部署      給与
3  高橋  28  人事  310000
4  伊藤  24  開発  340000

In [15]:
# DataFrame の情報を表示
print("DataFrame の情報:")
df.info()

DataFrame の情報:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   名前      5 non-null      object
 1   年齢      5 non-null      int64
 2   部署      5 non-null      object
 3   給与      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

### 3.4 列の追加・削除

In [16]:
# 新しい列を追加
df["入社年"] = [2022, 2019, 2015, 2018, 2020]
df

   名前  年齢  部署      給与   入社年
0  田中  22  営業  300000  2022
1  佐藤  25  開発  350000  2019
2  鈴木  30  営業  320000  2015
3  高橋  28  人事  310000  2018
4  伊藤  24  開発  340000  2020

In [17]:
# 計算で新しい列を作成（月給から年収を計算）
df["年収"] = df["給与"] * 12
df

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
1  佐藤  25  開発  350000  2019  4200000
2  鈴木  30  営業  320000  2015  3840000
3  高橋  28  人事  310000  2018  3720000
4  伊藤  24  開発  340000  2020  4080000

In [18]:
# 列を削除
df_dropped = df.drop(columns=["年収"])
print("年収列を削除:")
df_dropped

年収列を削除:

   名前  年齢  部署      給与   入社年
0  田中  22  営業  300000  2022
1  佐藤  25  開発  350000  2019
2  鈴木  30  営業  320000  2015
3  高橋  28  人事  310000  2018
4  伊藤  24  開発  340000  2020

### 📝 3章 練習問題

1. 以下の情報を持つ DataFrame を作成しなさい:
   - 列: 「商品名」「カテゴリ」「価格」「在庫数」
   - 行: 5 つ以上の商品
2. 作成した DataFrame の `shape`, `columns`, `dtypes` を確認しなさい。
3. 「価格」と「在庫数」を掛けて「在庫金額」という新しい列を追加しなさい。

In [19]:
# 練習問題の解答欄

---
## 4. データの読み込み・書き出し

pandas は様々な形式のデータを読み込めます。
ここでは最もよく使う CSV 形式を中心に学びます。

### 4.1 CSV への書き出し

In [20]:
# DataFrame を CSV 文字列に変換
csv_text = df.to_csv(index=False)
print("CSV 形式のテキスト:")
print(csv_text)

CSV 形式のテキスト:
名前,年齢,部署,給与,入社年,年収
田中,22,営業,300000,2022,3600000
佐藤,25,開発,350000,2019,4200000
鈴木,30,営業,320000,2015,3840000
高橋,28,人事,310000,2018,3720000
伊藤,24,開発,340000,2020,4080000

### 4.2 CSV からの読み込み

In [21]:
from io import StringIO

# 文字列から CSV を読み込む
df_loaded = pd.read_csv(StringIO(csv_text))
print("CSV から読み込んだ DataFrame:")
df_loaded

CSV から読み込んだ DataFrame:

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
1  佐藤  25  開発  350000  2019  4200000
2  鈴木  30  営業  320000  2015  3840000
3  高橋  28  人事  310000  2018  3720000
4  伊藤  24  開発  340000  2020  4080000

### 4.3 よく使う read_csv のオプション

```python
# 実際のファイルから読み込む場合の例
df = pd.read_csv(
    "data.csv",           # ファイルパス
    encoding="utf-8",     # 文字コード（日本語は utf-8 か shift_jis）
    header=0,             # ヘッダー行（0 が最初の行）
    index_col=None,       # インデックスに使う列
    usecols=["A", "B"],   # 読み込む列を指定
    nrows=100             # 最初の 100 行だけ読み込む
)
```

### 📝 4章 練習問題

1. 3章で作成した商品 DataFrame を CSV 形式の文字列に変換しなさい。
2. その CSV 文字列を `pd.read_csv` で読み込み、元の DataFrame と同じかどうか確認しなさい。
3. `to_csv` で `index=True` と `index=False` の違いを確認し、説明しなさい。

In [22]:
# 練習問題の解答欄

---
## 5. データの選択とスライス

DataFrame から特定の行や列を取り出す方法を学びます。

In [23]:
# サンプルデータの確認
df

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
1  佐藤  25  開発  350000  2019  4200000
2  鈴木  30  営業  320000  2015  3840000
3  高橋  28  人事  310000  2018  3720000
4  伊藤  24  開発  340000  2020  4080000

### 5.1 列の選択

In [24]:
# 1 列を選択（Series が返る）
df["名前"]

0    田中
1    佐藤
2    鈴木
3    高橋
4    伊藤
Name: 名前, dtype: object

In [25]:
# 複数列を選択（DataFrame が返る）
df[["名前", "年齢", "給与"]]

   名前  年齢      給与
0  田中  22  300000
1  佐藤  25  350000
2  鈴木  30  320000
3  高橋  28  310000
4  伊藤  24  340000

### 5.2 loc と iloc の違い

| メソッド | 指定方法 | 説明 |
|---------|---------|------|
| `loc` | ラベル | 行名・列名で指定 |
| `iloc` | 位置（番号）| 行番号・列番号で指定（0 から始まる）|

In [26]:
# loc: ラベルで選択
print("loc[0, '名前']:")
print(df.loc[0, "名前"])

print("\nloc[1:3, ['名前', '年齢']]:")
df.loc[1:3, ["名前", "年齢"]]  # 1〜3 行目（3 を含む）

loc[0, '名前']:
田中

loc[1:3, ['名前', '年齢']]:

   名前  年齢
1  佐藤  25
2  鈴木  30
3  高橋  28

In [27]:
# iloc: 位置（番号）で選択
print("iloc[0, 0]:")
print(df.iloc[0, 0])  # 0 行目、0 列目

print("\niloc[1:3, 0:2]:")
df.iloc[1:3, 0:2]  # 1〜2 行目（3 は含まない）、0〜1 列目

iloc[0, 0]:
田中

iloc[1:3, 0:2]:

   名前  年齢
1  佐藤  25
2  鈴木  30

### 5.3 loc と iloc の重要な違い

- `loc[1:3]` → 1, 2, 3 行目（**終端を含む**）
- `iloc[1:3]` → 1, 2 行目（**終端を含まない**、Python のスライスと同じ）

In [28]:
print("loc[0:2] - ラベル 0, 1, 2 の行（3 行）:")
print(df.loc[0:2, "名前"].tolist())

print("\niloc[0:2] - 位置 0, 1 の行（2 行）:")
print(df.iloc[0:2, 0].tolist())

loc[0:2] - ラベル 0, 1, 2 の行（3 行）:
['田中', '佐藤', '鈴木']

iloc[0:2] - 位置 0, 1 の行（2 行）:
['田中', '佐藤']

### 📝 5章 練習問題

1. `df` から「部署」列だけを取り出しなさい。
2. `loc` を使って、2 行目（インデックス 2）の「名前」と「給与」を取り出しなさい。
3. `iloc` を使って、最初の 3 行、最初の 2 列を取り出しなさい。
4. `loc` と `iloc` で同じ範囲を指定したとき、結果が異なる例を作り、その理由を説明しなさい。

In [29]:
# 練習問題の解答欄

---
## 6. 条件によるフィルタリング

条件を指定して、特定の行だけを抽出する方法を学びます。

### 6.1 単一条件でのフィルタリング

In [30]:
# 年齢が 25 歳以上の人
df[df["年齢"] >= 25]

   名前  年齢  部署      給与   入社年       年収
1  佐藤  25  開発  350000  2019  4200000
2  鈴木  30  営業  320000  2015  3840000
3  高橋  28  人事  310000  2018  3720000

In [31]:
# 条件式の中身を確認（True/False の Series）
print("df['年齢'] >= 25 の結果:")
print(df["年齢"] >= 25)

df['年齢'] >= 25 の結果:
0    False
1     True
2     True
3     True
4    False
Name: 年齢, dtype: bool

In [32]:
# 文字列の条件
df[df["部署"] == "営業"]

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
2  鈴木  30  営業  320000  2015  3840000

### 6.2 複数条件でのフィルタリング

複数条件を組み合わせるときは:
- AND（かつ）: `&`
- OR（または）: `|`
- NOT（否定）: `~`

**重要**: 各条件を `()` で囲むこと！

In [33]:
# 営業部 かつ 年齢が 25 歳以上
df[(df["部署"] == "営業") & (df["年齢"] >= 25)]

   名前  年齢  部署      給与   入社年       年収
2  鈴木  30  営業  320000  2015  3840000

In [34]:
# 営業部 または 開発部
df[(df["部署"] == "営業") | (df["部署"] == "開発")]

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
1  佐藤  25  開発  350000  2019  4200000
2  鈴木  30  営業  320000  2015  3840000
4  伊藤  24  開発  340000  2020  4080000

In [35]:
# isin を使うと複数の値を簡潔に指定できる
df[df["部署"].isin(["営業", "開発"])]

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
1  佐藤  25  開発  350000  2019  4200000
2  鈴木  30  営業  320000  2015  3840000
4  伊藤  24  開発  340000  2020  4080000

### 6.3 query メソッド

文字列で条件を書ける便利なメソッドです。

In [36]:
# query を使った書き方
df.query("年齢 >= 25 and 部署 == '営業'")

   名前  年齢  部署      給与   入社年       年収
2  鈴木  30  営業  320000  2015  3840000

### 📝 6章 練習問題

1. 給与が 320000 円以上の人を抽出しなさい。
2. 開発部で、かつ入社年が 2020 年以降の人を抽出しなさい。
3. 年齢が 25 歳未満、または給与が 340000 円以上の人を抽出しなさい。
4. `query` メソッドを使って、3 と同じ条件のフィルタリングを行いなさい。

In [37]:
# 練習問題の解答欄

---
## 7. 基本的な統計量の計算

pandas では、基本的な統計量を簡単に計算できます。

### 7.1 describe で概要を確認

In [38]:
# 数値列の基本統計量
df.describe()

              年齢             給与          入社年            年収
count   5.000000       5.000000     5.000000  5.000000e+00
mean   25.800000  324000.000000  2018.800000  3.888000e+06
std     3.193744   20736.441353     2.588436  2.488373e+05
min    22.000000  300000.000000  2015.000000  3.600000e+06
25%    24.000000  310000.000000  2018.000000  3.720000e+06
50%    25.000000  320000.000000  2019.000000  3.840000e+06
75%    28.000000  340000.000000  2020.000000  4.080000e+06
max    30.000000  350000.000000  2022.000000  4.200000e+06

### 7.2 個別の統計量

In [39]:
print(f"給与の平均: {df['給与'].mean():,.0f} 円")
print(f"給与の中央値: {df['給与'].median():,.0f} 円")
print(f"給与の標準偏差: {df['給与'].std():,.0f} 円")
print(f"給与の最大値: {df['給与'].max():,.0f} 円")
print(f"給与の最小値: {df['給与'].min():,.0f} 円")
print(f"給与の合計: {df['給与'].sum():,.0f} 円")

給与の平均: 324,000 円
給与の中央値: 320,000 円
給与の標準偏差: 20,736 円
給与の最大値: 350,000 円
給与の最小値: 300,000 円
給与の合計: 1,620,000 円

### 7.3 value_counts でカテゴリの頻度を確認

In [40]:
# 部署ごとの人数
print("部署ごとの人数:")
print(df["部署"].value_counts())

print("\n部署ごとの割合:")
print(df["部署"].value_counts(normalize=True))

部署ごとの人数:
部署
営業    2
開発    2
人事    1
Name: count, dtype: int64

部署ごとの割合:
部署
営業    0.4
開発    0.4
人事    0.2
Name: proportion, dtype: float64

### 7.4 相関係数

In [41]:
# 数値列間の相関係数
df[["年齢", "給与", "入社年"]].corr()

           年齢        給与       入社年
年齢   1.000000 -0.022649 -0.973774
給与  -0.022649  1.000000 -0.121099
入社年 -0.973774 -0.121099  1.000000

### 📝 7章 練習問題

1. `df` の年齢の平均と中央値を計算し、その差について考察しなさい。
2. 入社年ごとの人数を `value_counts` で求めなさい。
3. 年齢と給与の相関係数を計算し、その意味を解釈しなさい。
4. 部署ごとの給与の平均を計算しなさい（ヒント: `groupby` を使う）。

In [42]:
# 練習問題の解答欄

---
## 8. データの並べ替え

DataFrame の行を特定の列の値で並べ替える方法を学びます。

### 8.1 sort_values で並べ替え

In [43]:
# 年齢の昇順で並べ替え
df.sort_values("年齢")

   名前  年齢  部署      給与   入社年       年収
0  田中  22  営業  300000  2022  3600000
4  伊藤  24  開発  340000  2020  4080000
1  佐藤  25  開発  350000  2019  4200000
3  高橋  28  人事  310000  2018  3720000
2  鈴木  30  営業  320000  2015  3840000

In [44]:
# 給与の降順で並べ替え
df.sort_values("給与", ascending=False)

   名前  年齢  部署      給与   入社年       年収
1  佐藤  25  開発  350000  2019  4200000
4  伊藤  24  開発  340000  2020  4080000
2  鈴木  30  営業  320000  2015  3840000
3  高橋  28  人事  310000  2018  3720000
0  田中  22  営業  300000  2022  3600000

### 8.2 複数列での並べ替え

In [45]:
# 部署で昇順、その中で給与で降順
df.sort_values(["部署", "給与"], ascending=[True, False])

   名前  年齢  部署      給与   入社年       年収
3  高橋  28  人事  310000  2018  3720000
2  鈴木  30  営業  320000  2015  3840000
0  田中  22  営業  300000  2022  3600000
1  佐藤  25  開発  350000  2019  4200000
4  伊藤  24  開発  340000  2020  4080000

### 8.3 インデックスの並べ替え

In [46]:
# 並べ替え後、インデックスをリセット
df_sorted = df.sort_values("給与", ascending=False).reset_index(drop=True)
df_sorted

   名前  年齢  部署      給与   入社年       年収
0  佐藤  25  開発  350000  2019  4200000
1  伊藤  24  開発  340000  2020  4080000
2  鈴木  30  営業  320000  2015  3840000
3  高橋  28  人事  310000  2018  3720000
4  田中  22  営業  300000  2022  3600000

### 📝 8章 練習問題

1. `df` を入社年の古い順（昇順）に並べ替えなさい。
2. 部署で並べ替え、同じ部署内では年齢の若い順に並べ替えなさい。
3. 給与の高い順に並べ替えた後、`reset_index` でインデックスを振り直しなさい。
4. 並べ替え後に `head(3)` を使って、給与トップ 3 を表示しなさい。

In [47]:
# 練習問題の解答欄

---
## まとめ

このチュートリアルで学んだことをまとめます：

| トピック | 主なメソッド/属性 |
|---------|------------------|
| Series の作成 | `pd.Series()` |
| DataFrame の作成 | `pd.DataFrame()` |
| データの読み込み | `pd.read_csv()` |
| データの書き出し | `df.to_csv()` |
| 列の選択 | `df["列名"]`, `df[["列1", "列2"]]` |
| 行・列の選択 | `df.loc[]`, `df.iloc[]` |
| フィルタリング | `df[条件]`, `df.query()` |
| 基本統計量 | `df.describe()`, `.mean()`, `.sum()` など |
| 頻度集計 | `df["列"].value_counts()` |
| 並べ替え | `df.sort_values()` |

## 次のステップ

初級を終えたら、**pandas 中級チュートリアル** で以下を学びましょう：
- groupby による集計
- 欠損値の処理
- データの結合（merge, concat）
- データの変換（apply, map）
- 時系列データの処理

---
## 総合演習

以下のタスクに挑戦して、学んだ内容を確認しましょう。

### 課題：学生の成績データを分析する

1. 以下の列を持つ DataFrame を作成しなさい（10 人以上）：
   - 学籍番号、名前、学年、数学、英語、国語

2. 各科目の平均点と標準偏差を計算しなさい。

3. 3 科目の合計点を計算し、新しい列として追加しなさい。

4. 合計点の高い順に並べ替えて、上位 3 名を表示しなさい。

5. 学年ごとの合計点の平均を計算しなさい。

6. 数学が 80 点以上、かつ英語が 70 点以上の学生を抽出しなさい。

In [48]:
# 総合演習の解答欄